application: gdg-gigcity
version: 1b
runtime: go
api_version: go1

default_expiration: "30d"

handlers:
- url: /static/img
  static_dir: static/img

- url: /admin
  script: _go_app
  login: admin

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /(.*\.png)
  static_files: static/\1
  upload: static/(.*\.png)

- url: /favicon.ico
  mime_type: image/x-icon
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: _go_app
