application: gdg-gigcity
version: 1
runtime: go
api_version: go1

default_expiration: "4d 5h"

handlers:
- url: /static/img
  static_dir: static/img

- url: /admin
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
